"""
The shell hook: what actually attaches memory to a terminal.

zsh gives us three moments worth using, and the hook uses each for a
different half of the layer:

  chpwd    you walked into a project — recall what happened here last
  precmd   a command just finished — journal it, with its exit code
  zshexit  the shell is closing — fold the session into memory

The rules this obeys, in order of how badly they break things:

  Never block the prompt.  Journalling is fired into the background and
  disowned, so the cost you feel is the cost of `zsh` forking, not of
  Python starting. Distillation runs a language model and would be
  unthinkable inline; it goes to the background too, on exit.

  Never break the shell.  Every hook is wrapped so a failure inside
  memoos — a missing venv, a locked database, a half-finished install —
  can never take the exit code, the prompt, or the session with it.

  Never journal itself.  The hook's own commands are filtered out, or
  the log fills with memoos logging memoos.
"""

import os
import sys

from . import config

HOOK_FILENAME = "memoos.zsh"


def _install_root() -> str:
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _data_dir() -> str:
    """
    The one store every shell should write to, resolved absolutely.

    `config.DATA_DIR` is relative by default, and the hook runs from
    whatever directory you happen to be standing in — so left unpinned,
    the first `cd ~/other-project` grows a second, empty store there and
    silently splits your memory in half. Resolving it once, at install
    time, is what makes one terminal's journal the same journal as the
    next one's.

    A relative setting is anchored to the install root rather than the
    installer's cwd, so `memoos install` from anywhere puts the store
    beside the code instead of wherever you ran it from.
    """
    configured = os.path.expanduser(config.DATA_DIR)
    if os.path.isabs(configured):
        return os.path.normpath(configured)
    return os.path.normpath(os.path.join(_install_root(), configured))


def _hook_source() -> str:
    """The hook, bound to the interpreter that installed it."""
    python = sys.executable
    cli = os.path.join(_install_root(), "memoos_cli.py")
    return ZSH_TEMPLATE.format(python=python, cli=cli, data_dir=_data_dir())


ZSH_TEMPLATE = r'''# memoos — memory for your terminal.
# Generated by `memoos install`. Source this from ~/.zshrc.

export MEMOOS_PYTHON="{python}"
export MEMOOS_CLI="{cli}"

# Pinned at install time, because the default is a relative path and the
# hook runs from wherever you are standing. Left to resolve per-directory
# it would scatter a fresh, empty store into every project you visit.
export MEMOOS_DATA_DIR="${{MEMOOS_DATA_DIR:-{data_dir}}}"

# One id per shell, so a session can be distilled as a unit.
export MEMOOS_SESSION="${{MEMOOS_SESSION:-$(date +%s)-$$}}"

# The disconnect switch. Tested as a file, and tested on every command
# rather than cached, so `memoos disconnect` takes effect in terminals
# that are already open. A [[ -f ]] test costs one stat; starting Python
# only to have it exit costs fifty milliseconds, so the check belongs
# here, before anything is spawned.
export MEMOOS_FLAG="$HOME/.memoos/disconnected"

_memoos_connected() {{
  [[ -f "$MEMOOS_FLAG" ]] && return 1
  case "${{MEMOOS_OFF:-}}" in
    ""|0|false|no) return 0 ;;
    *) return 1 ;;
  esac
}}

# Fire and forget. The prompt must never wait on a Python process, so
# every call is backgrounded and disowned (&! is zsh for both at once).
_memoos_bg() {{
  ( "$MEMOOS_PYTHON" "$MEMOOS_CLI" "$@" >/dev/null 2>&1 ) &!
}}

# --- journal each command, with the exit code it finished with --------
_memoos_precmd() {{
  local code=$?
  _memoos_connected || return $code
  local last
  last=$(fc -ln -1 2>/dev/null)
  last="${{last#"${{last%%[![:space:]]*}}"}}"      # strip leading blanks

  # Don't journal the tool journalling you.
  case "$last" in
    memoos*|*MEMOOS_CLI*|"") return $code ;;
  esac

  MEMOOS_CWD="$PWD" _memoos_bg log "$code" "$last"
  return $code
}}

# --- walking into a project shows you what happened here last ---------
_memoos_chpwd() {{
  [[ -o interactive ]] || return 0
  [[ -d .git ]] || return 0
  _memoos_connected || return 0
  "$MEMOOS_PYTHON" "$MEMOOS_CLI" recall --limit 4 2>/dev/null
}}

# --- closing the shell folds the session into memory ------------------
_memoos_zshexit() {{
  _memoos_connected || return 0
  _memoos_bg distill --session "$MEMOOS_SESSION"
}}

autoload -Uz add-zsh-hook 2>/dev/null
if (( $+functions[add-zsh-hook] )); then
  add-zsh-hook precmd  _memoos_precmd
  add-zsh-hook chpwd   _memoos_chpwd
  add-zsh-hook zshexit _memoos_zshexit
fi

# `memoos` on your PATH, without installing a package.
#
# `connect --here` / `disconnect --here` are handled in the shell rather
# than passed through, because they set an environment variable in *this*
# terminal and a subprocess cannot do that to its parent. Everything else
# goes straight to the CLI.
memoos() {{
  if [[ "$2" == "--here" ]]; then
    case "$1" in
      disconnect) export MEMOOS_OFF=1
                  print -r -- "disconnected for this terminal only"; return 0 ;;
      connect)    unset MEMOOS_OFF
                  print -r -- "connected for this terminal"; return 0 ;;
    esac
  fi
  "$MEMOOS_PYTHON" "$MEMOOS_CLI" "$@"
}}
'''

def __getattr__(name: str):
    """
    `ZSH_HOOK` rendered on access, so `memoos install --print-only` shows
    exactly what would be written. It cannot be a plain module attribute:
    the hook embeds the path of the interpreter importing it, which is
    not known until then.
    """
    if name == "ZSH_HOOK":
        return _hook_source()
    raise AttributeError(name)


def hook_path() -> str:
    return os.path.expanduser(os.path.join("~/.memoos", HOOK_FILENAME))


def install_hook() -> str:
    """Write the hook to ~/.memoos/memoos.zsh and return the path."""
    path = hook_path()
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(_hook_source())
    return path
